openapi: 3.0.0
info:
  contact:
    email: yoshihisa.wada@yo41sawada.jp
    name: none
    url: https://example.com/
  description: 自動生成させるモデルを定義
  title: OpenAPI generator サンプル
  version: "1.0"
servers:
  - url: http://localhost:3000
paths:
  /users:
    get:
      description: ユーザーの一覧を返す。
      operationId: get-users
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/User'
                type: array
          description: OK
      summary: Your GET endpoint
      tags:
        - users
      x-accepts: application/json
      x-tags:
        - tag: users
  /user/{id}:
    get:
      description: ユーザーを返す。
      operationId: get-user
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: int32
            type: integer
          style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: OK
      summary: Your GET endpoint
      tags:
        - users
      x-accepts: application/json
      x-tags:
        - tag: users
components:
  schemas:
    User:
      example:
        last_name: last_name
        id: 0
        first_name: first_name
      properties:
        id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
      required:
        - first_name
        - last_name
      title: User
      type: object
