version: "3.8"

volumes:
  db-store:

services:
  backend:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ..:/workspace:cached
  db:
    image: postgres:14
    container_name: postgres4yo41sawada
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
